server:
  port: 80
wechat:
  #  微信公众平台的appID
  appId: 'wx80164088624e309e'
  #  微信公众平台的appSecret
  secret: 'ebba773682b1a53d50f9a1557fbceea6'
  #  百度地图开放平台的城市ID
  district_id: '610900'
  #  百度地图开放平台的应用AK
  ak: '8PNy95KdoINFHQcxQGZ0M6sr0xOViFVw'
  #  纪念日：注意格式yyyy-MM-dd
  loveDate: '2020-12-25'
  #  生日：注意格式yyyy-MM-dd （无论是计算阳历生日还是农历生日,一律填阳历出生年月日）
  birthday: '1998-04-17'
  #  模板ID
  templateId: 'YNOMSnZFekB3YefrExKDRvPSFS4Sw8kNUOkxN3DvsDE'
  #  天行数据apiKey
  rainbowKey: '2705ee4c35fe23f8d59ec91ed7b029a1'
  #  关注公众号的用户ID（要推送的人的用户ID,在微信公众平台里可以查看到,现在支持推送多个人）
  userId:
    - 'oMSS950woNQ9gj8SxRZdZAHr1j48'
    - 'oMSS95y5Qom2PdwQmL0B3qZTbHtw'

  #    是否按农历计算生日 true:是 false:否
  useLunar: true
  #  cron表达式
  cron: 0 0 8 * * ?